apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: expections
    meta.helm.sh/release-namespace: exceptions
  labels:
    app: ssd
    app.kubernetes.io/managed-by: Helm
    chart: ssd-2024.07.00
    component: token-machine
    heritage: Helm
    release: expections
  name: token-machine
spec:
  selector:
    matchLabels:
      app: ssd
      component: token-machine
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ssd
        chart: ssd-2024.07.00
        component: token-machine
        heritage: Helm
        release: expections
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: opsmx11/token-machine:99eb752-7
        imagePullPolicy: IfNotPresent
        name: token-machine
        ports:
        - containerPort: 8099
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opsmx/config/
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: token-machine
      serviceAccountName: token-machine
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: token-machine
        name: config-volume
